uncomment org precommit hook

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -12,14 +12,14 @@ then
   exit 1
 fi
 
-# if [[ $ORG_NAME == "REPLACE_ORG_NAME" ]] || [[ $ORG_EMAIL == "REPLACE_ORG_EMAIL" ]]
-# then
-#   echo "ERROR: Fix pre-commit org name or email."
-#   exit 1
-# else
-#   if [[ $REMOTE_URL_ORIGIN == *$ORG_NAME* ]] && [[ ! $USER_EMAIL == *$ORG_EMAIL* ]]
-#   then
-#     echo "ERROR: incorrect email ($USER_EMAIL) for $REMOTE_URL_ORIGIN"
-#     exit 1
-#   fi
-# fi
+if [[ $ORG_NAME == "REPLACE_ORG_NAME" ]] || [[ $ORG_EMAIL == "REPLACE_ORG_EMAIL" ]]
+then
+  echo "ERROR: Fix pre-commit org name or email."
+  exit 1
+else
+  if [[ $REMOTE_URL_ORIGIN == *$ORG_NAME* ]] && [[ ! $USER_EMAIL == *$ORG_EMAIL* ]]
+  then
+    echo "ERROR: incorrect email ($USER_EMAIL) for $REMOTE_URL_ORIGIN"
+    exit 1
+  fi
+fi
